### ISSUE TITLE
"KOMOREBI_CONFIG_HOME Is Required" despite correct configuration

### ISSUE THREAD

**Issue by tieniu1** [starise/komorebi-tray#4]
![image](https://github.com/user-attachments/assets/cca174a6-4d88-499c-8225-561f42161696)
I'm getting the error `KOMOREBI_CONFIG_HOME Is Required` even though I have properly configured the environment variable.

**Comment by tieniu1** [comment]
I added komorebi-tray to the environment variables and ran komorebi-tray using PowerShell with the KOMOREBI_CONFIG_HOME variable set. Now it can read the configuration correctly.
However, if I directly double-click komorebi-tray.exe, it still cannot load KOMOREBI_CONFIG_HOME properly.

**Comment by starise** [comment]
Please, try adding `KOMOREBI_CONFIG_HOME` as env var with this command:
```powershell
# Set KOMOREBI_CONFIG_HOME for the user
PS> [System.Environment]::SetEnvironmentVariable("KOMOREBI_CONFIG_HOME", "C:\Users\haland\.config\komorebi", "User")

# Check configuration
PS> [System.Environment]::GetEnvironmentVariable("KOMOREBI_CONFIG_HOME", "User")
C:\Users\haland\.config\komorebi #expected output
```

Then try again double-clicking `komorebi-tray.exe`.

**Comment by tieniu1** [comment]
> Please, try adding `KOMOREBI_CONFIG_HOME` as env var with this command:请尝试用这条命令添加 `KOMOREBI_CONFIG_HOME` 作为环境变量：
> 
> ```powershell
> # Set KOMOREBI_CONFIG_HOME for the user
> PS> [System.Environment]::SetEnvironmentVariable("KOMOREBI_CONFIG_HOME", "C:\Users\haland\.config\komorebi", "User")
> 
> # Check configuration
> PS> [System.Environment]::GetEnvironmentVariable("KOMOREBI_CONFIG_HOME", "User")
> C:\Users\haland\.config\komorebi #expected output
> ```
> 
> Then try again double-clicking `komorebi-tray.exe`.然后再次双击 `komorebi-tray.exe` 。



> Please, try adding `KOMOREBI_CONFIG_HOME` as env var with this command:
> 
> ```powershell
> # Set KOMOREBI_CONFIG_HOME for the user
> PS> [System.Environment]::SetEnvironmentVariable("KOMOREBI_CONFIG_HOME", "C:\Users\haland\.config\komorebi", "User")
> 
> # Check configuration
> PS> [System.Environment]::GetEnvironmentVariable("KOMOREBI_CONFIG_HOME", "User")
> C:\Users\haland\.config\komorebi #expected output
> ```
> 
> Then try again double-clicking `komorebi-tray.exe`.

I have successfully set up the KOMOREBI_CONFIG_HOME environment variable, and I've configured it in both PowerShell 7 and Windows PowerShell. It's now working properly.
Thank you for your help.

**Comment by tieniu1** [comment]
I still have a question. Why is it that after using komorebi-tray and selecting default.ahk, the hotkeys are not working, although switching workspaces is displaying correctly?

**Comment by starise** [comment]
> I still have a question. Why is it that after using komorebi-tray and selecting default.ahk, the hotkeys are not working, although switching workspaces is displaying correctly?

Check if there are multiple `AutoHotkey *` background processes in Task Manager, try to close all of them and restart komorebi-tray. There are some issues I noticed with the tray because komorebi only has a command to start ahk, but not to stop it, it's maybe something that should be done by komorebi itself and not by this tray app, I'm not sure, I should ask komorebi mantainer about this.

**Comment by tieniu1** [comment]
> > I still have a question. Why is it that after using komorebi-tray and selecting default.ahk, the hotkeys are not working, although switching workspaces is displaying correctly?
> 
> Check if there are multiple `AutoHotkey *` background processes in Task Manager, try to close all of them and restart komorebi-tray. There are some issues I noticed with the tray because komorebi only has a command to start ahk, but not to stop it, it's maybe something that should be done by komorebi itself and not by this tray app, I'm not sure, I should ask komorebi mantainer about this.

Thank you for your reply！
